version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.15.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
            - 8089:8089
        networks:
            - elknetwork
    logstash:
        image: logstash:7.15.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - .\logstash:/usr/share/logstash/pipeline/
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
networks:
    elknetwork:
        driver: bridge
